# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-ParallelPort-drv-linux
version:      1.00
version_from: linux.pm
installdirs:  site
requires:
    Device::ParallelPort:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
